### ISSUE TITLE
NPM do not works

### ISSUE THREAD

**Issue by wilfredonoyola** [ngTrumbitta/ngx-fit-text#1]
Please you sure the register it in  https://registry.npmjs.org.

Thanks,

**Comment by trumbitta** [comment]
Hi, can you please elaborate on what error you are getting and maybe also the versions of node and npm you are using?

I'm still using it and it still works for me.

**Comment by wilfredonoyola** [comment]
The error : 
![npm error](https://user-images.githubusercontent.com/1428168/36441490-7484a8e4-1638-11e8-9c3e-b85bab0c5863.JPG)

I am using node version v6.11.1 and npm version 3.10.10. I think that I need update it.

**Comment by trumbitta** [comment]
Good catch!

There was a typo in the README file from whence you got the installation command. I already fixed it.

Please, try the following and let me know it works:

```
npm install ngx-fit-text -S
```

**Comment by trumbitta** [comment]
Also, yes, I haven't tested it with node 6 and npm 3. Please, do try and let me know if it also works with those versions.

**Comment by wilfredonoyola** [comment]
Now works for me.. I am using IONIC 3 and I hope that work good!
Thanks for it!

**Comment by wilfredonoyola** [comment]
Also I have tested in IONIC 3 , It is works good!
